/*
 * Test.java
 *
 * Created on __DATE__, __TIME__
 */

package com.hellocode.ui.simple;

import javax.swing.Icon;
import javax.swing.ImageIcon;

import com.hellocode.ui.simple.FlexiRangeModel.Range;

/**
 * 
 * @author __USER__
 */
public class Test extends javax.swing.JFrame {

	/** Creates new form Test */
	public Test() {
		initComponents();
		this.init();
	}

	private void init() {
		this.slider = new JFlexiSlider(new Range[] { new Range("A", true,80),
				new Range("B", false,80), new Range("C", true, 80) }, new Icon[]{new ImageIcon("code_logo.png"),new ImageIcon("code_logo.png"),new ImageIcon("code_logo.png"),new ImageIcon("code_logo.png")},
				new String[] { "1A-M", "2B-m-f", "3C-t-l", "4Another-t-l" });
		//this.add(this.slider);
		this.getContentPane().add(
				this.slider,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1,
						-1));
	}

	private JFlexiSlider slider = null;

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		getContentPane().setLayout(
				new org.netbeans.lib.awtextra.AbsoluteLayout());

		jButton1.setText("Test");
		getContentPane().add(
				jButton1,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1,
						-1));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Test().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	// End of variables declaration//GEN-END:variables

}